# This is a basic workflow to help you get started with Actions

name: Build proxy.pac

# Controls when the action will run. 
on:
  schedule:    
    - cron: "0 0 * * 0"
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'

    - name: Setup Go 1.x.y
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'

    - name: Set $GOPATH and more variables
      run: |
        echo "REPO_URL=github.com/${{ github.repository }}" >> $GITHUB_ENV
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        echo "REPO2_URL=github.com/v2fly/domain-list-community" >> $GITHUB_ENV
      shell: bash
        
    - name: Go get project code
      run: |
        go install -v $REPO_URL
          
    - name: Build dlc.dat file
      run: |
        git clone https://github.com/v2fly/domain-list-community.git
        antiGFW --datapath=domain-list-community/data
     
    - name: Build proxy.pac file
      run: |
        python3 -m pip install -U https://github.com/tomyangsh/genpac/archive/fix.zip
        genpac --gfwlist-url - --gfwlist-local gfwlist.txt --pac-proxy "SOCKS5 127.0.0.1:7890; SOCKS 127.0.0.1:7890" > 7890.pac
        genpac --gfwlist-url - --gfwlist-local gfwlist.txt --pac-proxy "SOCKS5 127.0.0.1:1089; SOCKS 127.0.0.1:1089" > 1089.pac
        genpac --gfwlist-url - --gfwlist-local gfwlist.txt --pac-proxy "SOCKS5 127.0.0.1:9001; SOCKS 127.0.0.1:9001" > 9001.pac

    - name: Push proxy.pac file
      run: |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git add *.pac
        git commit -m "update proxy.pac"
        git push
      

      
